{{- if .Values.sparql.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trifid.fullname" . }}
type: Opaque
stringData:
  sparql-password: {{ .Values.sparql.password }}
{{- end }}
